# Arquivo de configuração de segredos para o Streamlit Cloud
# Este arquivo NÃO deve ser commitado no repositório
# No Streamlit Cloud, configure estes valores nas configurações do app

[redis]
url = "redis://localhost:6379"
password = ""

[shopify]
api_key = ""
api_secret = ""
store_url = ""